baseURL = 'https://www.davesmith.dev'
languageCode = 'en-us'
title = 'Dave Smith'
theme = 'PaperMod'
enableEmoji = true

enableRobotsTXT = true
buildFuture = false
buildExpired = false

[params]
ShowShareButtons = true
ShowCopyCodeButtons = true
Author = "Me"
AuthorImage = "images/me.jpg"
comments = "true"
disableSpecial1stPost = true
customCSS = ["css/custom.css"]

[params.homeInfoParams]
Title = "Hey, I’m Dave 👋"
Content = "I run code by day, and run trails by night. I'm a software engineer who debugs in .NET and JavaScript, compiles miles in the woods, and occasionally catches a runtime error on the running track. When I'm not deploying applications, I'm deploying myself into nature - though my Go skills are currently faster than my actual go speed"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/smithcommadave"

[[params.socialIcons]]
name = "bluesky"
url = "https://bluesky.app/davesmith.dev"

[[params.socialIcons]]
name = "github"
url = "https://github.com/dave-smith"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/smithcommadave/"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/posts/"
weight = 20
