baseURL = 'https://www.davesmith.dev'
languageCode = 'en-us'
title = 'Dave Smith'
theme = 'PaperMod'


enableRobotsTXT = true
buildFuture = false
buildExpired = false

[params]
ShowShareButtons = true
ShowCopyCodeButtons = true
Author = "Me"
AuthorImage = "images/me.jpg"
comments = "true"
disableSpecial1stPost = true
customCSS = ["css/custom.css"]

[params.homeInfoParams]
Title = "Hi, I’m Dave 👋"
Content = """
I occupy the small intersection of people who love writing code and people who think running really, really, long miles is actually fun 🏃‍➡️

{{< new_line >}}
I'm based in the midwest as a lead software developer pushing out code for the often ignored but quite interesting bond markets (no, not jail bonds, think treasuries and munis). When I get some time away from the compiler I will likely be out for a run on the Ice Age trail

{{< new_line >}}
In addition to race reports and training updates, I enjoy writing about Go. C#, JavaScript and SQL are my day-to-day so I have a lot to say about those. You'll see me writing about  AI dev tooling and machine learning in financial services as I work these tools
"""

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/smithcommadave"

[[params.socialIcons]]
name = "bluesky"
url = "https://bluesky.app/davesmith.dev"

[[params.socialIcons]]
name = "github"
url = "https://github.com/dave-smith"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/smithcommadave/"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "notes"
name = "Notes"
url = "/notes/"
weight = 30

[security]
  enableInlineShortcodes = true